### ISSUE TITLE
How to use specific timecode?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [phuochau/react-native-thumbnail#1]
I'd like to extract an image from a specific moment in the video. Possible?

**Comment by phuochau** [comment]
Hi @GeoffreyPlitt currently, I only get the first frame as thumbnail. But your idea is interesting, I will add more options to get at a specific moment.

**Comment by japantopdeveloper** [comment]
Hi, @phuochau 
I got the thumbnail on Android version perfectly, but I cannot get it on iOS version at all.
The width and height are 0, so the image is not opened.
What was wrong?

**Comment by MendyK** [comment]
@GeoffreyPlitt Saw your comments on other repos. Did you figure out a way of getting the thumbnail from a specific time in the video?

**Comment by GeoffreyPlitt** [comment]
Yes, we switched to https://github.com/shahen94/react-native-video-processing
