### ISSUE TITLE
How should the filepath be?

### ISSUE THREAD

**Issue by ronastlelobo** [phuochau/react-native-thumbnail#29]
I am using [react-native-document-picker](https://github.com/Elyx0/react-native-document-picker). I get the file path using the res object, `res.uri` give me file path in the form of content://com.android.providers.media.documents/document/video%xxxxxxx. On giving this file path to `RNThumbnail.get(res.uri)` my app crashes. I don't know whether there is problem with `uri`  or anything else.

**Comment by nitinkumar24** [comment]
@ronastlelobo Did you find any solution?

**Comment by ronastlelobo** [comment]
No

**Comment by nitinkumar24** [comment]
You can use RnFetchBlob to get the exact path of an image.
   RNFetchBlob.fs
              .stat(uri)
              .then(stats => {
                filepath = stats.path;
                console.log(filepath);
              })

**Comment by heyman333** [comment]
you have to use local file url that init with `file://` 
you can use `rn-fetch-blob' or 'react-native-real-path`
