### ISSUE TITLE
Doesn't work on iOS version.

### ISSUE THREAD

**Issue by japantopdeveloper** [phuochau/react-native-thumbnail#6]
Hi, there.
I got the thumbnail as an image on Android version, but I didn't get it on iOS version well.
I got the path, but the width and height were 0.
What is wrong?

I am using RN 0.44.0.

**Comment by phuochau** [comment]
@japantopdeveloper sorry for late response, I have a little bit busy in my company projects. I will take a look on today or tomorrow to update for latest RN version

**Comment by MendyK** [comment]
I'm having the same problem

**Comment by phuochau** [comment]
Fixed for RN 0.47.0, please check again

**Comment by MendyK** [comment]
@phuochau Does it work for lower versions of RN too?

**Comment by rf1804** [comment]
I am facing this issue, in android it's working fine but in ios the output is


```
height:0
path:"/var/mobile/Containers/Data/Application/19659288-B148-4D66-8DB5-31458334AF50/Library/Caches/thumb-C5B7D3EB-7D90-4379-9A75-2644884F5236-4224-000005F0DCC25E7B.jpg"
width:0
```

"react-native": "0.51.0"
"react-native-thumbnail": "^1.1.0"
