### ISSUE TITLE
We don't need "@Override" for android, aren't we?

### ISSUE THREAD

**Issue by kikill95** [phuochau/react-native-thumbnail#7]
I think that we don't need "@Override" for ```public List<Class<? extends JavaScriptModule>>``` method, when I am trying run "react-native run-android" I have compile error:

```
/node_modules/react-native-thumbnail/android/src/main/java/com/reactlibrary/RNThumbnailPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
```

When I remove "@Override" this works and compile fine

I am not good in Java, but I think we can do it.

Line that I think we need to remove: https://github.com/phuochau/react-native-thumbnail/blob/master/android/src/main/java/com/reactlibrary/RNThumbnailPackage.java#L19

**Comment by prscX** [comment]
Hi @kikill95 

I have raised a PR for the same [8](https://github.com/phuochau/react-native-thumbnail/pull/8)

I hope it will be merged ASAP. Meantime you can remove @override and use this library

Thanks
Pranav

**Comment by kikill95** [comment]
Hi, @prscX 

Thank you

**Comment by phuochau** [comment]
Just updated the npm package, pls check, thanks @prscX for making PR

**Comment by Doko-Demo-Doa** [comment]
I see, merged. Thank you guys.
